FROM rust:1-alpine as build

WORKDIR /usr/src/app
COPY . .
COPY ./.sqlx .

RUN apk add --no-cache musl-dev pkgconfig openssl libressl-dev
ENV SQLX_OFFLINE true
RUN cargo build --release

FROM alpine

# COPY --from=build /usr/local/cargo/bin/backend /usr/local/bin/backend
COPY --from=build /usr/src/app/target/release/f1-dash-backend /usr/local/bin/f1-dash-backend

CMD ["f1-dash-backend"]
