export const driverLookUp = [
  {
    number: 44,
    displayName: "HAM",
    team: "Mercedes",
    lineType: "SOLID",
    color: "#6CD3BF",
  },
  {
    number: 63,
    displayName: "RUS",
    team: "Mercedes",
    lineType: "DOT",
    color: "#6CD3BF",
  },
  {
    number: 55,
    displayName: "SAI",
    team: "Ferrari",
    lineType: "DOT",
    color: "#F91536",
  },
  {
    number: 16,
    displayName: "LEC",
    team: "Ferrari",
    lineType: "SOLID",
    color: "#F91536",
  },
  {
    number: 1,
    displayName: "VER",
    team: "Red Bull",
    lineType: "SOLID",
    color: "#3671C6",
  },
  {
    number: 11,
    displayName: "PER",
    team: "Red Bull",
    lineType: "DOT",
    color: "#3671C6",
  },
  {
    number: 81,
    displayName: "PIA",
    team: "McLaren",
    lineType: "DOT",
    color: "#F58020",
  },
  {
    number: 15,
    displayName: "NOR",
    team: "McLaren",
    lineType: "SOLID",
    color: "#F58020",
  },
  {
    number: 14,
    displayName: "ALO",
    team: "Aston Martin",
    lineType: "SOLID",
    color: "#358C75",
  },
  {
    number: 18,
    displayName: "STR",
    team: "Aston Martin",
    lineType: "DOT",
    color: "#358C75",
  },
  {
    number: 10,
    displayName: "GAS",
    team: "Alpine",
    lineType: "SOLID",
    color: "#2293D1",
  },
  {
    number: 31,
    displayName: "OCO",
    team: "Alpine",
    lineType: "DOT",
    color: "#2293D1",
  },
  {
    number: 22,
    displayName: "TSU",
    team: "AlphaTauri",
    lineType: "SOLID",
    color: "#5E8FAA",
  },
  {
    number: 21,
    displayName: "DEV",
    team: "AlphaTauri",
    lineType: "DOT",
    color: "#5E8FAA",
  },
  {
    number: 27,
    displayName: "HUL",
    team: "Haas F1 Team",
    lineType: "SOLID",
    color: "#B6BABD",
  },
  {
    number: 20,
    displayName: "MAG",
    team: "Haas F1 Team",
    lineType: "DOT",
    color: "#B6BABD",
  },
  {
    number: 24,
    displayName: "ZHO",
    team: "Alfa Romeo",
    lineType: "DOT",
    color: "#C92D4B",
  },
  {
    number: 77,
    displayName: "BOT",
    team: "Alfa Romeo",
    lineType: "SOLID",
    color: "#C92D4B",
  },
  {
    number: 2,
    displayName: "ALB",
    team: "Williams",
    lineType: "SOLID",
    color: "#37BEDD",
  },
  {
    number: 23,
    displayName: "SAR",
    team: "Williams",
    lineType: "DOT",
    color: "#37BEDD",
  },
];
