FROM rust:1-alpine as build

WORKDIR /usr/src/app
COPY . .
COPY ./.sqlx .

RUN apk add --no-cache musl-dev pkgconfig openssl libressl-dev
RUN cargo build --release

FROM alpine

COPY --from=build /usr/src/app/target/release/live-backend /usr/local/bin/live-backend

CMD ["live-backend"]
