FROM node:20-alpine AS base

WORKDIR /app
COPY package*.json ./
COPY yarn.lock ./


RUN corepack enable yarn

RUN yarn install --frozen-lockfile

COPY . .

RUN yarn build

FROM node:20-alpine AS runtime

WORKDIR /app

COPY --from=base /app/.next ./.next
COPY --from=base /app/node_modules ./node_modules
COPY --from=base /app/package.json ./package.json
COPY --from=base /app/public ./public

ENV NODE_ENV=production

EXPOSE 3000

CMD ["yarn", "start"]
