FROM node:22-alpine AS dependencies

WORKDIR /app
COPY package*.json yarn.lock .yarnrc.yml ./

RUN corepack enable

RUN yarn install --immutable

FROM dependencies AS builder

ARG ENABLE_TRACKING
ARG LIVE_SOCKET_URL
ARG API_URL

ENV NEXT_PUBLIC_ENABLE_TRACKING=$ENABLE_TRACKING
ENV NEXT_PUBLIC_LIVE_SOCKET_URL=$LIVE_SOCKET_URL
ENV NEXT_PUBLIC_API_URL=$API_URL

ENV NEXT_TELEMETRY_DISABLED=1
ENV SKIP_ENV_VALIDATION=1
ENV BUILD_STANDALONE=1

COPY . .

RUN yarn build

FROM node:22-alpine AS runtime

WORKDIR /app

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

ENV NEXT_TELEMETRY_DISABLED=1

ENV NODE_ENV=production
ENV HOSTNAME="0.0.0.0"

EXPOSE 3000

ENTRYPOINT [ "node", "server.js" ]
